### ISSUE TITLE
Logging object with circular reference

### ISSUE THREAD

**Issue by agoops** [benbria/bunyan-debug-stream#13]
Hi,
I noticed that when trying to log an object with a circular reference, bunyan-debug-stream throws an error: `TypeError: Converting circular structure to JSON`. 

It seems that's the case because it calls `JSON.stringify` [here](https://github.com/benbria/bunyan-debug-stream/blob/9141ee9938f5d53e221fcd7be014120ad63f87a3/src/BunyanDebugStream.coffee#L209).

Is there a way to override that with something like[`util.inspect`](https://nodejs.org/api/util.html#util_util_inspect_object_options) so that circular references are handled when converted to strings?

An example case showing the circular reference:
```javascript
var bunyanDebugStream = require('bunyan-debug-stream');
var bunyan = require('bunyan');

var log = bunyan.createLogger({
    name: "myLog",
    streams: [{
        level:  'info',
        type:   'raw',
        stream: bunyanDebugStream({
            forceColor: true
        })
    }],
});

let b = {a: "temp"};
const a = {b: b};
b.a = a;

log.info(a);
```
throws 
```bash
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at BunyanDebugStream._entryToString (/temp/node_modules/bunyan-debug-stream/lib/BunyanDebugStream.js:206:30)
    at BunyanDebugStream._write (/temp/node_modules/bunyan-debug-stream/lib/BunyanDebugStream.js:253:28)
    at doWrite (_stream_writable.js:397:12)
    at writeOrBuffer (_stream_writable.js:383:5)
    at BunyanDebugStream.Writable.write (_stream_writable.js:290:11)
    at Logger._emit (/temp/node_modules/bunyan/lib/bunyan.js:923:22)
    at Logger.info (/temp/node_modules/bunyan/lib/bunyan.js:1045:24)
    at Object.<anonymous> (/bunyandebug-test.js:20:5)
    at Module._compile (module.js:652:30)

```
Thanks!

**Comment by jwalton** [comment]
Good catch!  I'd happily take a PR.
